### ISSUE TITLE
Is the Sign in endpoint out of date?

### ISSUE THREAD

**Issue by avenmia** [jzarca01/node-nikerunclub#2]
Hey @jzarca01 ,  I'm having trouble signing into the nike run app with this. Is the api endpoint to sign in still relevant? I've tried using postman, but all my requests say unauthorized. If it's out of date, what were the steps you took to get the endpoint last time?

**Comment by jzarca01** [comment]
The endpoint used to get the access_token in the first place has been terminated by Nike a while ago, but it's still used to get a refresh_token.

I managed to find a way to sign in again, but unfortunately it relies on Puppeteer so the api is not fully backend anymore.
Let me know if you have any other issues (other than to sign in).
